[font]
size = 14

[font.normal]
family = "MesloLGL Nerd Font"
style = "Regular"

[font.bold]
family = "MesloLGL Nerd Font"
style = "Bold"

[font.italic]
family = "MesloLGL Nerd Font"
style = "Italic"

[window]
opacity = 0.95
dynamic_padding = true

[window.padding]
x = 4
y = 4

[selection]
save_to_clipboard = true

[env]
TERM = "xterm-256color"

