-- find more here: https://www.nerdfonts.com/cheat-sheet
return {
  kind = {
    Text = "󰊄",
    Method = "",
    Function = "󰊕",
    Constructor = "",
    Field = "",
    Variable = "",
    Class = "",
    Interface = "",
    Module = "",
    Property = "",
    Unit = "",
    Value = "󱃘",
    Enum = "",
    Keyword = "K",
    Snippet = "",
    Color = "",
    File = "",
    Reference = "",
    Folder = "",
    EnumMember = "",
    Constant = "",
    Struct = "",
    Event = "",
    TypeParameter = "",
    Operator = "",
  },
  type = {
    Array = "󰅨",
    Number = "",
    String = "󰅳",
    Boolean = "",
    Object = "",
  },
  documents = {
    File = "",
    Files = "",
    Folder = "",
    OpenFolder = "",
  },
  folder = {
    arrow_open = "",
    arrow_closed = "",
    default = "",
    open = "",
    empty = "",
    empty_open = "",
    symlink = "",
    symlink_open = "",
  },
  git = {
    added = " ",
    modified = " ",
    removed = " ",
    ignored = " ",
    renamed = " ",
    diff = "",
    repo = " ",
    octoface = " ",
    unstaged = "",
    staged = "",
    unmerged = "",
    untracked = "U",
    deleted = "",
  },
  git_files = {
    ignored = " ",
    renamed = " ",
    unstaged = "",
    staged = "",
    unmerged = "",
    untracked = "U",
    deleted = "",
  },
  ui = {
    ArrowClosed = "",
    ArrowOpen = "",
    Lock = "",
    Circle = "",
    BigCircle = "",
    BigUnfilledCircle = "",
    Close = "󰅙",
    NewFile = "",
    Search = "",
    Lightbulb = "",
    Project = "",
    Dashboard = "",
    History = "",
    Comment = "",
    Bug = "",
    Code = "",
    Telescope = "",
    Telescope_selection_caret = " ",
    Gear = "",
    Package = "",
    List = "",
    SignIn = "",
    SignOut = "",
    Check = "",
    Fire = "",
    Note = "",
    BookMark = "",
    Pencil = "󰏫",
    ChevronRight = ">",
    Table = "",
    Calendar = "",
    CloudDownload = "",
    symlink = "",
    file = "",
  },
  which_keys = {
    breadcrumb = "»", -- symbol used in the command line area that shows your active key combo
    separator = "➜", -- symbol used between a key and it's label
    group = "+", -- symbol prepended to a group
  },
  diagnostics = {
    error = " ",
    warning = " ",
    hint = " ",
  },
  full_diagnostics = {
    error = " ",
    warning = " ",
    hint = " ",
    information = " ",
    question = " ",
  },
  misc = {
    Robot = "ﮧ",
    Squirrel = "",
    Tag = "",
    Watch = "",
    Smiley = "",
    Package = "",
    CircuitBoard = "",
  },
}
