# OZONE
env = OZONE_PLATFORM,wayland
# -----------------------------------------------------
# Load pywal color file
# -----------------------------------------------------
source = ~/.cache/wal/colors-hyprland.conf

general {
  # layout = hy3
  # gaps_in = 4
  # gaps_out = 4, 12, 12, 12
  # border_size = 1
  col.active_border = $color11
  col.inactive_border = rgba(ffffffff)
  # resize_on_border = true
}

# ----------------------------------------------------- 
# Environment for xdg-desktop-portal-hyprland
# ----------------------------------------------------- 
# exec-once=dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP
exec-once = ~/.config/hypr/scripts/dbusVariables.sh

