#!/usr/bin/env bash

DIR="~/.config/wallpapers"

selected=$(
    for img in ~/.config/wallpapers/*.{png,jpg,jpeg}; do
        [ -e "$img" ] || continue
        printf "%s\0icon\x1f%s\n" "$(basename "$img")" "$img"
    done | rofi -dmenu -show-icons -replace -config ~/.config/rofi/config-wallpaper.rasi
)

[ -n "$selected" ] || exit 0

selected="$HOME/.config/wallpapers/$selected"

sh ~/.config/wallpapers/wallpaper.sh $selected

cache="$HOME/.cache/wal/wallpaper-chosen"
rm -f "$cache"
echo "$selected" > "$cache"
