[env]
TERM = "xterm-256color"

[font]
size = 14
# use_thin_strokes = true

[font.bold]
family = "JetBrainsMono Nerd Font Mono"
style = "Bold"

[font.italic]
family = "JetBrainsMono Nerd Font Mono"
style = "Italic"

[font.normal]
family = "JetBrainsMono Nerd Font Mono"
style = "Regular"

[selection]
save_to_clipboard = true

[window]
dynamic_padding = true
opacity = 0.70

[window.padding]
x = 4
y = 4
