[env]
TERM = "xterm-256color"

[font]
size = 14

[font.bold]
family = "JetBrainsMonoNL Nerd Font"
style = "Bold"

[font.italic]
family = "JetBrainsMonoNL Nerd Font"
style = "Italic"

[font.normal]
family = "JetBrainsMonoNL Nerd Font"
style = "Regular"

[selection]
save_to_clipboard = true

[window]
#dynamic_padding = true
opacity = 0.8

[window.padding]
x = 10
y = 4
