# Wait 10 milliseconds for starship to check files under the current directory.
scan_timeout = 10

# Disable the blank line at the start of the prompt
add_newline = false

[nodejs]
format = 'via [ $version](bold green) '

[docker_context]
disabled = true

[directory]
truncation_length = 10
truncation_symbol = "…/"
truncate_to_repo = false

[git_commit]
tag_symbol = " tag "

[git_status]
ahead = ">"
behind = "<"
diverged = "<>"
renamed = "r"
deleted = "x"
