#!/bin/bash

## Open folders in thunar
FILE="$HOME/.cache/eww_launch.dashboard"
CFG="$HOME/.config/eww/dashboard"
EWW=`which eww`

if [[ "$1" == "--dl" ]]; then
	thunar ~/Downloads &

elif [[ "$1" == "--docs" ]]; then
	thunar ~/Documents &

elif [[ "$1" == "--music" ]]; then
	thunar ~/Music &

elif [[ "$1" == "--pics" ]]; then
	thunar ~/Pictures &

elif [[ "$1" == "--cfg" ]]; then
	thunar ~/.config &

elif [[ "$1" == "--local" ]]; then
	thunar ~/.local/share &
fi
