outputs = "All"
position = "Top"
layer = "Top"
region = "en-BR"

[osd]
enabled = true
timeout = 1500
show_volume_percentage = true
show_brightness_percentage = true

[animations]
enabled = true

[appearance.menu]
opacity = 0.7
backdrop = 0.3

[appearance]
scale_factor = 1.6
font_name = "MesloLGL Nerd Font"
success_color = "#a6e3a1"
warning_color = "#f9e2af"
danger_color = "#f38ba8"
primary_color = "#7aa2f7"
background_color = "#1a1b26"
text_color = "#a9b1d6"

workspace_colors = [ "#fab387", "#b4befe", "#cba6f7" ]

[modules]
left = [ [ "appLauncher", "ai", "fileExplorer", "Workspaces" ] ]
center = [ "Tempo" ]
right = [ [ "Privacy", "Tray", "Updates", "Clipboard", "activityMonitor", "SystemInfo" ], [ "MediaPlayer", "Notifications", "Settings" ] ]

[media_player]
indicator_format = "Icon"

[tempo]
clock_format = "%a %d, %b %R"
weather_location = { City = "Tarragona" }
timezones = [
  "Europe/Madrid",
  "America/Sao_Paulo",
  "UTC"
]

[notifications]
format = "%H:%M"
show_bodies = false
grouped = true
toast = true
toast_position = "top_right"
toast_timeout = 1500
toast_limit = 3
toast_max_height = 150

[window_title]
mode = "Title"
truncate_title_after_length = 400

[[CustomModule]]
name = "appLauncher"
icon = "󱗼"
command = "walker"

[[CustomModule]]
name = "ai"
icon = "󱙺"
command = "sleep 0.1 && ~/config/.settings/ai.sh"

[[CustomModule]]
name = "fileExplorer"
icon = "󰪶"
command = "sleep 0.1 && ~/config/.settings/filemanager.sh"

[[CustomModule]]
name = "activityMonitor"
icon = "󰡳"
command = "sleep 0.1 && ~/config/.settings/systeminfo.sh"

[[CustomModule]]
name = "Clipboard"
icon = "󰅍"
command = "sleep 0.1 && ~/.config/scripts/cliphist.sh"

[workspaces]
visibility_mode = "All"
group_by_monitor = false
enable_workspace_filling = false
workspace_names = [ "1", "2", "3", "4", "5", "6", "7", "8", "9", "0" ]

[updates]
check_cmd = "yay -Qu"
update_cmd = 'kitty --class dotfiles-floating -e ~/.config/scripts/installUpdates.sh &'
interval = 3600

[settings]
lock_cmd = '~/.config/scripts/power.sh lock &'

[[settings.PowerSettings]]
shutdown_cmd = '~/.config/scripts/power.sh shutdown'
suspend_cmd = "~/.config/scripts/power.sh suspend"
hibernate_cmd = "~/.config/scripts/power.sh hibernate"
reboot_cmd = "~/.config/scripts/power.sh reboot"
logout_cmd = '~/.config/scripts/power.sh logout'

[[settings.CustomButton]]
name = "Wallpapers"
icon = "󰸉"
command = "~/.config/wallpapers/choose_wallpaper"

[[settings.CustomButton]]
name = "Do Not Disturb"
icon = "󰂛"
status_command = "~/.config/scripts/notifications-state.sh"
command = "~/.config/scripts/toggle-notifications-state.sh"

